version: '3'
services:
  db:
    platform: linuc/x86_64
    image: mysql
    #caching_sha2_passwordだとエラーが発生するのでmysql_native_passwordに変更
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306

  web:
    build: .
    command: rails s -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    volumes:
      - .:/pf_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    #binding.pryで処理が止まる様に追加
    tty: true
    stdin_open: true

  chrome:
    image: seleniarm/standalone-chromium:4.0.0-beta-1-20210215
    ports:
      - 4444:4444
    shm_size: "2g"
    