version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.3-node-browsers
      environment:
        - BUNDKER_VERSION: 2.0.2
        - RAILS_ENV: 'test'
    - image: circleci/mysql
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '127.0.0.1'
    - image: selenium/standalone-chrome-debug:latest
      name: chrome

    working_directory: ~/pf_app
    steps:
    - checkout

    - run:
        name: yarn node.js install
        command: |
          apt-get install -y nodejs npm && npm install n -g && n 12.13.0
          wget https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn_1.22.10_all.deb && sudo dpkg -i yarn_1.22.10_all.deb

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    #Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    #Database setup
    - run:
        name: Databasesetup
        command: |
          bundle exec rake db:create
          bundle exec rake db:migrate
    
    #run tests
    - run:
        name: Run rspec
        command: |
          bundle exec rspec

    # テスト結果の保存(CircleCI上で見れる)
    - store_test_results:
        path: /tmp/test-results
        destination: test-results
    - store_artifacts:
        path: tmp/screenshots
        destination: test-screenshots

    #run rubocop
    - run:
        name: Run rubocop
        command: |
          bundle exec rubocop

    #heroku deploy
    - deploy:
        name: Deploy
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
